name: tflite_flutter_plugin_example
description: Demonstrates how to use the tflite_flutter_plugin plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.26.0-17.6.pre"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: 0.9.0
  path_provider: ^2.0.1
  cupertino_icons: ^0.1.2
  translator: ^0.1.7
  firebase: ^9.0.2
  firebase_auth: ^3.1.2
  firebase_database: ^8.0.0
  firebase_core: ^1.7.0
  flutter_svg: ^0.22.0
  cloud_firestore: ^2.5.3
  firebase_storage: ^10.1.0
  image_picker: ^0.8.5+3
  flutter_image_slideshow: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter    


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/test/
    - assets/images/
    - assets/images/bg/
    - assets/images/ic/
    - assets/images/banner/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
